<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TableproductSeeder extends Seeder
{
    public function run()
    {
        $data = [

            [
                'id' => 1,
                'name' => "Pot Keramik",
                'slug' => 'product01',
                'description' => "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi, sapiente.",
                'type' => "0",
                'cover' => "sample_pot.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 30000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 2,
                'name' => "Tas Anyaman Bambu",
                'slug' => 'product02',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, necessitatibus?",
                'type' => "0",
                'cover' => "sample_tas_bambu.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 250000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 3,
                'name' => "Kain Tenun",
                'slug' => 'product03',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur, repellendus!",
                'type' => "0",
                'cover' => "sample_kain_tenun.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 75000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 4,
                'name' => "Patung Garuda Kayu",
                'slug' => 'product04',
                'description' => "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque tenetur ut animi amet dicta accusamus?",
                'type' => "0",
                'cover' => "sample_patung_garuda.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 2000000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 5,
                'name' => "Kalung Manik-manik",
                'slug' => 'product05',
                'description' => "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis placeat, laboriosam at corrupti beatae cumque!",
                'type' => "0",
                'cover' => "sample_kalung_manik.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 19550,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 6,
                'name' => "Akuarium Kaca",
                'slug' => 'product06',
                'description' => "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, optio.",
                'type' => "0",
                'cover' => "sample_akuarium.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 450000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 11,
                'name' => "Bawang Merah Brebes 1kg",
                'slug' => 'product11',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, molestias!",
                'type' => "1",
                'cover' => "sample_bawang_merah.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 28000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 12,
                'name' => "Beras Medium Lampung 1kg",
                'slug' => 'product12',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic, veniam! ",
                'type' => "1",
                'cover' => "sample_beras_lampung.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 13600,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 13,
                'name' => "Gabah Cianjur 1kg",
                'slug' => 'product13',
                'description' => "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse, corporis! ",
                'type' => "1",
                'cover' => "sample_gabah_cianjur.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 7000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 14,
                'name' => "Gabah Grobogan 1kg",
                'slug' => 'product14',
                'description' => "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, nihil. ",
                'type' => "1",
                'cover' => "sample_gabah_grobogan.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 7800,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 15,
                'name' => "Gabah Lampung 1kg",
                'slug' => 'product15',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, laboriosam ratione fugiat reiciendis mollitia similique. ",
                'type' => "1",
                'cover' => "sample_gabah_lampung.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 8000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 16,
                'name' => "Jagung Lampung",
                'slug' => 'product16',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum, rem pariatur? Quidem suscipit dolorum iste, quod amet atque! ",
                'type' => "1",
                'cover' => "sample_jagung_lampung.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 5100,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 17,
                'name' => "Jagung Tasikmalaya 1kg",
                'slug' => 'product17',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, fuga. ",
                'type' => "1",
                'cover' => "sample_jagung_tasikmalaya.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 4600,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 18,
                'name' => "Kakao Kendari 1kg",
                'slug' => 'product18',
                'description' => "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, odio voluptatibus minus maiores ipsam suscipit ad beatae harum earum. ",
                'type' => "1",
                'cover' => "sample_kakao_kendari.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 54000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 21,
                'name' => "Ikan Tuna 1kg",
                'slug' => 'product21',
                'description' => "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor sapiente rerum ex culpa quasi numquam nisi tempore exercitationem placeat, nemo maiores quo laudantium labore omnis? ",
                'type' => "2",
                'cover' => "sample_ikan_tuna.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 15000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 22,
                'name' => "Lobster Laut Frozen 1Kg",
                'slug' => 'product22',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos ullam, quod unde nemo ratione quisquam, tempora eaque sapiente autem rerum repellat voluptates consequuntur ducimus nesciunt. ",
                'type' => "2",
                'cover' => "sample_lobster.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 95000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],

            [
                'id' => 23,
                'name' => "Cumi Sotong Kering 1Kg",
                'slug' => 'product23',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam dolor necessitatibus assumenda sequi error vitae quod laudantium nostrum nisi! Corporis ad maiores animi officia! Velit corrupti repellendus laudantium deserunt ab! ",
                'type' => "2",
                'cover' => "sample_cumi.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 65000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],

            [
                'id' => 24,
                'name' => "Kerang Tahu Hidup 1Kg",
                'slug' => 'product24',
                'description' => "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis quos deleniti explicabo. Ipsa maxime culpa delectus, quam laboriosam modi velit, soluta perferendis cum, optio neque. Aliquam ullam maiores error et! ",
                'type' => "2",
                'cover' => "sample_kerang_tahu.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 22000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 31,
                'name' => "Batu Bara 1kg",
                'slug' => 'product31',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates ab quibusdam dolores dicta reprehenderit ad beatae nisi veniam quaerat tempore! ",
                'type' => "3",
                'cover' => "sample_batu_bara.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 60790,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
            [
                'id' => 32,
                'name' => "Anoda Nikel 99% 1Kg",
                'slug' => 'product32',
                'description' => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam quam architecto et ipsam sed nulla a eum ut aut alias? ",
                'type' => "3",
                'cover' => "sample_nikel.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 574900,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],

            [
                'id' => 33,
                'name' => "Plat Tembaga Busbar 15mm x 60mm x 100mm",
                'slug' => 'product33',
                'description' => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Impedit dolorum nostrum ad deserunt enim doloremque illum, esse voluptatem architecto tempore inventore veniam iste accusamus maiores a labore rem eum voluptatibus. ",
                'type' => "3",
                'cover' => "sample_plat_tembaga.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 240000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],

            [
                'id' => 34,
                'name' => "Timah Lunak Batangan  1Kg",
                'slug' => 'product34',
                'description' => "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur maxime eius officiis aliquid expedita impedit, laborum deserunt nihil voluptatem ab. ",
                'type' => "3",
                'cover' => "sample_timah.jpg",
                'postalcode' => 10250,
                'id_user' => 8,
                'weight' => 100,
                'stock' => 1,
                'price' => 40000,
                'created_at' => '2024-02-14 00:00:00',
                'updated_at' => '2024-02-14 00:00:00',
            ],
        ];

        // Simple Queries
        //$this->db->query('INSERT INTO users (username, email) VALUES(:username:, :email:)', $data);

        // Using Query Builder
        // $this->db->table('tableproduct')->insert($data);
        $this->db->table('tableproduct')->insertBatch($data);
    }
}
